#!/bin/bash
#

# extargs="--png --nsteps=10000 --burnfrac=0.4"
extargs="--nsteps=10000 --burnfrac=0.4 --png"
# extargs="--png"
fit="python utils/fit_mir_ext_powerlaw.py"

rm -f fits/*POWLAW2DRUDE.h5

# V stars
$fit fits/hd204827_hd036512_ext.fits $extargs
$fit fits/cygob2-1_hd214680_ext.fits $extargs
$fit fits/hd147889_hd064802_ext.fits $extargs
$fit fits/hd029309_hd064802_ext.fits $extargs
$fit fits/hd283809_hd064802_ext.fits $extargs
$fit fits/hd281159_hd064802_ext.fits $extargs
$fit fits/hd147933_hd031726_ext.fits $extargs

# III stars
$fit fits/hd147701_hd195986_ext.fits $extargs
$fit fits/hd029647_hd195986_ext.fits $extargs
$fit fits/bd+63d1964_hd188209_ext.fits $extargs

# I stars
$fit fits/cygob2-8a_hd188209_ext.fits $extargs
$fit fits/hd192660_hd204172_ext.fits $extargs
$fit fits/hd229238_hd204172_ext.fits $extargs
$fit fits/hd112272_hd204172_ext.fits $extargs
$fit fits/cygob2-2_hd214680_ext.fits $extargs
$fit fits/hd014956_hd204172_ext.fits $extargs
