#!/bin/bash
#

extargs="--png --nsteps=5000 --burnfrac=0.4"
# extargs="--png"
fit="python utils/fit_ext_p92.py"

rm -f fits/*P92.h5

# V stars
$fit fits/hd204827_hd036512_ext.fits $extargs
$fit fits/vicyg1_hd214680_ext.fits $extargs
$fit fits/hd147889_hd064802_ext.fits $extargs
$fit fits/hd029309_hd064802_ext.fits $extargs
$fit fits/hd283809_hd064802_ext.fits $extargs
$fit fits/hd281159_hd064802_ext.fits $extargs

# III stars
$fit fits/hd147701_hd195986_ext.fits $extargs
$fit fits/hd029647_hd195986_ext.fits $extargs
$fit fits/bd+63d1964_hd188209_ext.fits $extargs

# I stars
$fit fits/vicyg8a_hd188209_ext.fits $extargs
$fit fits/hd192660_hd204172_ext.fits $extargs
$fit fits/hd229238_hd204172_ext.fits $extargs
$fit fits/hd112272_hd204172_ext.fits $extargs
$fit fits/vicyg2_hd214680_ext.fits $extargs
$fit fits/hd014956_hd204172_ext.fits $extargs
